### ISSUE TITLE
Awkward wording on the Code of Conduct page

### ISSUE THREAD

**Issue by ptrcnull** [servo/servo.org#164]
( for what it's worth, maybe it's just on me being a non-native speaker, but )

the following sentence:
> The Servo Project follows the [Rust Code of Conduct](https://www.rust-lang.org/policies/code-of-conduct), with two differences.

reads a bit weird - especially in the context of the [text that immediately follows][1], which lists a single difference, and then a list of people you can contact..?

i assume the two differences are meant to be:
- it applies to Servo, and not Rust
- you should contact Servo moderators and not Rust ones

but then still, i think a bullet list (or maybe even a numbered list) could improve it

[1]: https://github.com/servo/servo.org/blob/f0283df0978f5fa9de408c78f10a4acd135fede4/coc.md?plain=1#L11

**Comment by mrego** [comment]
@delan could you help to reword/clarify this? BTW keep it in sync with https://github.com/servo/project/blob/main/CODE_OF_CONDUCT.md

Thanks!
