### ISSUE TITLE
Move text from Layout to Content

### ISSUE THREAD

**Issue by paulrouget** [servo/servo.org#19]
This needs to me migrated under /content/:

* https://github.com/servo/servo.org.staging/blob/master/layouts/partials/home/download.html#L19
* https://github.com/servo/servo.org.staging/blob/master/layouts/partials/home/hero.html#L11

**Comment by mrego** [comment]
The website has changed and those files are no longer in the repository.

There are some text in some templates under `_includes/` now, but it doesn't look like a big priority to move them away from the templates at this point, so I'm closing this.
