### ISSUE TITLE
/hl-home/ no more exists

### ISSUE THREAD

**Issue by Rufus31415** [servo/servo.org#34]
Firefox Reality home page on Hololens 2 returns a 404 not found.

The page is : https://servo.org/hl-home

**Comment by mrego** [comment]
I think we can close this, Firefox Reality is now [Wolvic](https://wolvic.com/en/start/).

A similar kind of page can be found at https://wolvic.com/en/start/.

I don't think there's any plan about adding a similar page in servo.org anytime soon.
