### ISSUE TITLE
Where are the minutes from 2021-02-12?

### ISSUE THREAD

**Issue by MailYouLater** [servo/servo.org#38]
Hello, I was just looking at the website and found that the most recent of the TSC meeting minutes linked at https://servo.org/governance/tsc/readme/#meetings is both mislabeled, and missing.

First, as far as I can tell, the meeting occurred in 2021, but the text of the link is "12 Feb 2020".

Second, the link goes to is to a "tsc-2021-02-12.md", which doesn't seem to exist, either on the website, or in this repository.

For reference, this is where the link is in this repo.
https://github.com/servo/servo.org/blob/9dfa3bd4ab91ba2a571d730a98cf332050af2fce/content/governance/tsc/README.md?plain=1#L36

I'm genuinely interested in reading these meeting minutes, but ... can't seem to find them.
- Related: #36

**Comment by jdm** [comment]
We started keeping notes at https://github.com/servo/project/tree/master/governance/tsc instead. I don't remember why that switch occurred.

**Comment by mrego** [comment]
Minutes are now linked from https://servo.org/governance/tsc/readme/#meetings
