### ISSUE TITLE
TSC governance page is out of date

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo.org#39]
https://servo.org/governance/tsc/readme/ has some stale and missing information.

Should the *Mettings* section be replaced with a link to https://github.com/servo/project/tree/master/governance/tsc ? See also https://github.com/servo/servo.org/issues/38

**Comment by mrego** [comment]
This should be fixed by https://github.com/mrego/servo.org/commit/25a75fe10ed8acba0e1fe38cad5aa8cfc99c7354, but deployment seems to be failing.

**Comment by mrego** [comment]
This has now been deployed.
